### ISSUE TITLE
Browsing errorhandling not correct

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/dashboard#18]
```
31 Mar 2014 19:55:12,096 [eXistThread-43] WARN  (ServletHandler.java [doHandle]:492) -  
javax.servlet.ServletException: An error occurred while processing request to /exist/apps/dashboard/plugins/browsing/contents/: err:XPDY0002 variable '$err:message' is not set. [at line 31, column 24, source: /db/apps/dashboard/plugins/browsing/service.xql]
In function:
    service:delete-resources(xs:string*) [46:43:/db/apps/dashboard/plugins/browsing/service.xql]
    restxq:call-with-args(function, function*) [88:17:/db/apps/dashboard/modules/restxq.xql]
    (function, element(), map) [83:68:/db/apps/dashboard/modules/restxq.xql]
    restxq:function-by-annotation(function+, map, function) [83:9:/db/apps/dashboard/modules/restxq.xql]
    restxq:process(xs:string?, function+) [49:9:/db/apps/dashboard/modules/restxq.xql]
    at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:386)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)

Caused by: org.exist.xquery.XPathException: err:XPDY0002 variable '$err:message' is not set. [at line 31, column 24, source: /db/apps/dashboard/plugins/browsing/service.xql]
In function:
    service:delete-resources(xs:string*) [46:43:/db/apps/dashboard/plugins/browsing/service.xql]
    restxq:call-with-args(function, function*) [88:17:/db/apps/dashboard/modules/restxq.xql]
    (function, element(), map) [83:68:/db/apps/dashboard/modules/restxq.xql]
    restxq:function-by-annotation(function+, map, function) [83:9:/db/apps/dashboard/modules/restxq.xql]
    restxq:process(xs:string?, function+) [49:9:/db/apps/dashboard/modules/restxq.xql]
    at org.exist.xquery.VariableReference.eval(VariableReference.java:87)
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)

```

**Comment by joewiz** [comment]
@dizzzz I assume this is fixed in dashboard 2.x, but if not please open a new issue referencing the version tested.
