### ISSUE TITLE
Scheduler UI does not work on 'develop'

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/dashboard#41]
Clicking the UI [todays development] yields into the following trace:

```
2016-04-01 14:48:03,757 [eXistThread-36] WARN  (ServletHandler.java [doHandle]:563) - /exist/apps/dashboard/plugins/scheduler/scheduler.html
org.exist.xquery.XPathException: err:XPST0081 error found while loading module service: Error while loading module service.xql: No namespace defined for prefix xqueries
        at org.exist.dom.QName.parse(QName.java:298) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.primaryExpr(XQueryTreeParser.java:6983) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3489) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.numericExpr(XQueryTreeParser.java:8205) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3542) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.functionCall(XQueryTreeParser.java:9808) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.primaryExpr(XQueryTreeParser.java:6994) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3489) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.functionCall(XQueryTreeParser.java:9808) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.primaryExpr(XQueryTreeParser.java:6994) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3489) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:416) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:1839) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.constructor(XQueryTreeParser.java:9338) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.constructor(XQueryTreeParser.java:9197) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.primaryExpr(XQueryTreeParser.java:6792) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3489) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:320) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.primaryExpr(XQueryTreeParser.java:6930) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3489) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:413) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:2567) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.functionDecl(XQueryTreeParser.java:5543) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.prolog(XQueryTreeParser.java:4686) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.libraryModule(XQueryTreeParser.java:3951) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.module(XQueryTreeParser.java:3785) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.xpath(XQueryTreeParser.java:3569) ~[exist.jar:?]
        at org.exist.xquery.XQueryContext.compileModule(XQueryContext.java:2919) ~[exist.jar:?]
        at org.exist.xquery.XQueryContext.compileOrBorrowModule(XQueryContext.java:2857) ~[exist.jar:?]
        at org.exist.xquery.XQueryContext.importModule(XQueryContext.java:2772) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.importDecl(XQueryTreeParser.java:5654) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.prolog(XQueryTreeParser.java:4693) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.mainModule(XQueryTreeParser.java:3963) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.module(XQueryTreeParser.java:3908) ~[exist.jar:?]
        at org.exist.xquery.parser.XQueryTreeParser.xpath(XQueryTreeParser.java:3569) ~[exist.jar:?]
        at org.exist.xquery.XQuery.compile(XQuery.java:133) ~[exist.jar:?]
        at org.exist.xquery.XQuery.compile(XQuery.java:84) ~[exist.jar:?]
        at org.exist.xquery.XQuery.compile(XQuery.java:75) ~[exist.jar:?]
        at org.exist.http.urlrewrite.XQueryURLRewrite.runQuery(XQueryURLRewrite.java:686) ~[exist-optional.jar:?]
        at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:260) ~[exist-optional.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[servlet-api-3.0.jar:?]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) ~[jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496) ~[jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
        at de.betterform.agent.web.filter.XFormsFilter.doFilter(XFormsFilter.java:171) ~[betterform-exist-5.1-SNAPSHOT-20151014.jar:?]

```

**Comment by joewiz** [comment]
The Scheduler pane was removed from the UI in https://github.com/eXist-db/dashboard/commit/214d58a95068b892988f10a737c80932048edec1.
