### ISSUE TITLE
Java Admin Client Error

### ISSUE THREAD

**Issue by welblaud** [eXist-db/dashboard#43]
I like the Java Admin app but for an unknown reason, I am not able to start it (since, let’s say, February). I thought it could be because of some new Java version but it is the same on Linux and Win 10 or Win 7 machine.

After the verification, it throws an error (window). In the Details section there is:

```
com.sun.deploy.net.JARSigningException: Found unsigned entry in resource: http://46.28.111.241:8081/exist/webstart/exist.jar
	at com.sun.javaws.security.SigningInfo.getCommonCodeSignersForJar(Unknown Source)
	at com.sun.javaws.security.SigningInfo.check(Unknown Source)
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResourcesHelper(Unknown Source)
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareAllResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.launch(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
and 
```
<?xml version="1.0" ?><jnlp spec="7.0" codebase="http://46.28.111.241:8081/exist/webstart/" href="exist.jnlp"><information><title>eXist XML-DB client</title><vendor>exist-db.org</vendor><homepage href="http://exist-db.org"></homepage><description>Integrated command-line and gui client, entirely based on the XML:DB API and provides commands for most database related tasks, like creating and removing collections, user management, batch-loading XML data or querying.</description><description kind="short">eXist XML-DB client</description><description kind="tooltip">eXist XML-DB client</description><icon href="jnlp_logo.jpg"></icon><icon href="jnlp_icon_128x128.gif" width="128" height="128"></icon><icon href="jnlp_icon_64x64.gif" width="64" height="64"></icon><icon href="jnlp_icon_32x32.gif" width="32" height="32"></icon></information><security><all-permissions/></security><resources><property name="jnlp.packEnabled" value="true"></property><java version="1.8+"></java><jar href="xmlrpc-common-3.1.3.jar" size="122351"></jar><jar href="sunxacml-1.2.jar" size="210074"></jar><jar href="jline-0.9.94.jar" size="93057"></jar><jar href="rsyntaxtextarea-2.5.6.jar" size="1081139"></jar><jar href="xmlrpc-client-3.1.3.jar" size="65437"></jar><jar href="ws-commons-util-1.0.2.jar" size="38457"></jar><jar href="log4j-jul-2.3.jar" size="24060"></jar><jar href="slf4j-api-1.7.10.jar" size="36571"></jar><jar href="exist.jar" size="4482013"></jar><jar href="xmldb.jar" size="12722"></jar><jar href="commons-io-2.4.jar" size="198441"></jar><jar href="log4j-slf4j-impl-2.3.jar" size="25551"></jar><jar href="log4j-core-2.3.jar" size="889605"></jar><jar href="excalibur-cli-1.0.jar" size="25946"></jar><jar href="log4j-api-2.3.jar" size="146688"></jar><jar href="commons-pool-1.6.jar" size="118633"></jar></resources><application-desc main-class="org.exist.client.InteractiveClient"><argument>-ouri=xmldb:exist://46.28.111.241:8081/exist/xmlrpc</argument><argument>--no-embedded-mode</argument></application-desc></jnlp>
```

**Comment by dizzzz** [comment]
Again: which excist-db version?

Did you (re)build exist-db yourself?
- If not: Please clean the webstart cache and retry
- If so: you need to rebuild eXist with jar signing switched on

see documentation (needs to  be updated)
- http://www.exist-db.org/exist/apps/doc/java-admin-client.xml

**Comment by welblaud** [comment]
It is 3.0.RC1. No, I didn’t build it myself. I will try the last nightly build and let you know.

**Comment by dizzzz** [comment]
Please clean Tour webstart cache .... That helps probably

**Comment by welblaud** [comment]
Well, cleaning the cache did not help. I tried that on Linux Mint machine (there is Iced Tea version used) and on a Win 7 machine (classical WebStart). Still the same. For 3.0.RC1 and #d084a50 as well. I guess there could be something between eXist and my desktop clients but have no clue what. Thanks.

**Comment by joewiz** [comment]
Honza,

Sounds like you're starting the client by accessing a server's .jnlp file.
To do that I believe you have to have run the jar signer build step on the
binaries on the server (from $EXIST_HOME):

  ./build.sh -f build/scripts/jarsigner.xml

An alternative, if you have eXist on your system, is to start the client
locally,

  bin/client.sh

See http://exist-db.org/exist/apps/doc/java-admin-client.xml for more
info.  If you are still having problems, please detail the steps you use to
start the client.

Joe

**Comment by welblaud** [comment]
Joe, thanks, it really works! I wonder how I was able to run it during the winter without this step. These errors started much later and I was not able to solve that. Thanks again.

**Comment by joewiz** [comment]
Good, glad this helped!
